services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - 5432:5432
    volumes:
      - pg_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

volumes:
  pg_vol:
